title: Songxin Lei's Homepage
page-top-title: Songxin Lei
top-section-bg-text: Data Science
home-subtitle: Songxin Lei&ensp;|&ensp;雷松鑫
copyright-text: '&copy; Songxin Lei 2024-2025. All Rights Reserved.'
